name: shop
description: FlutterShop is a premium E-commerce UI kit that you can use to build various e-commerce apps using Flutter that works on both Android & iOS. This kit contains 100+ nicely crafted minimal screens that cover everything you need for your shop app.

publish_to: "none"

version: 1.0.0+8

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.3.2
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  path_provider: ^2.1.2
  open_filex: ^4.3.2
  cached_network_image: ^3.2.0
  animations: ^2.0.11
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  flutter_html: ^3.0.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.3.2
  dropdown_search: ^6.0.2
  showcaseview: ^3.0.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# --- Configuration for Launcher Icons ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/tlkeys-icon.png"
  min_sdk_android: 21

# --- Configuration for Native Splash Screen ---
flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo/logo.png"

# --- Main Flutter Configuration ---
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/flags/
    - assets/logo/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic